package fan.summer.database.entity;

import lombok.Data;

/**
 * Entity representing the display order of menu items in the sidebar.
 * <p>
 * Stores the ordering configuration for tool pages, allowing the sidebar
 * navigation to be rendered in a user-defined or persisted sequence.
 *
 * @since 3.0.0
 */
@Data
public class MenuOrderEntity {
    /** Primary key, auto-generated by the database. */
    private Integer id;

    /** The fully-qualified class name of the tool page (e.g., {@code com.example.MyToolPage}). */
    private String pageClass;

    /** Numeric order value; lower values appear higher in the sidebar. */
    private Integer menuOrder;
}
