package fan.summer.database.mapper.setting.email;

import fan.summer.database.entity.setting.email.EmailTagEntity;

import java.util.List;

/**
 * MyBatis mapper interface for {@link fan.summer.database.entity.setting.email.EmailTagEntity}.
 *
 * <p>Provides CRUD operations for email tag records stored in the H2 database.
 *
 * @see fan.summer.database.entity.setting.email.EmailTagEntity
 */
public interface EmailTagMapper {
    /**
     * Inserts a new email tag record.
     *
     * @param emailTagEntity the tag entity to insert; id may be generated by the DB
     */
    void insert(EmailTagEntity emailTagEntity);

    /**
     * Updates an existing email tag record.
     *
     * @param emailTagEntity the tag entity with updated values; must include the primary key
     */
    void update(EmailTagEntity emailTagEntity);

    /**
     * Retrieves all email tag records ordered by insertion order.
     *
     * @return list of all EmailTagEntity records
     */
    List<EmailTagEntity> selectAll();

    /**
     * Deletes an email tag by its primary key.
     *
     * @param id the primary key of the tag to delete
     */
    void deleteById(Long id);
}
