// Generated by FengYu Toolchain. Do not edit.

import type { FengYuClient, InvokeOptions } from '@infinia/plugin-sdk'

export type RenderInput = {
  source: string
}

export type RenderOutput = {
  html: string
}

export type SummarizeInput = {
  lines: string[]
}

export type SummarizeOutput = {
  summary: string | null
}

export interface PluginRpc {
  render(input: RenderInput, options?: InvokeOptions): Promise<RenderOutput>
  summarize(input: SummarizeInput, options?: InvokeOptions): Promise<SummarizeOutput>
}

export function createPluginRpc(client: FengYuClient): PluginRpc {
  return {
    render: (input, options) => client.invoke<RenderOutput>('render', input, options),
    summarize: (input, options) => client.invoke<SummarizeOutput>('summarize', input, options),
  }
}
