// Generated by FengYu Toolchain. Do not edit.
package fan.summer.example.generated;

public final class PluginMethods {
  private PluginMethods() {}

  public static final String RENDER = "render";
  public static final String SUMMARIZE = "summarize";
}
