// Generated by FengYu Toolchain. Do not edit.
package fan.summer.example.generated;

import com.google.gson.annotations.SerializedName;

public record RenderOutput(
    @SerializedName("html") String html
) {}
