// Generated by FengYu Toolchain. Do not edit.
package fan.summer.example.generated;

import com.google.gson.annotations.SerializedName;
import java.util.List;

public record SummarizeInput(
    @SerializedName("lines") List<String> lines
) {}
