import { chromium } from '/Users/phoebej/Develop/Java/FengYu/desktop/electron/node_modules/playwright/index.mjs'
const browser = await chromium.launch({ executablePath: '/Users/phoebej/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing' })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://localhost:5173/', { waitUntil: 'load', timeout: 15000 }).catch(() => {})
await page.waitForTimeout(2000)
await page.click('.sidebar-user-button')
await page.waitForTimeout(400)
await page.locator('.sidebar-account-menu-item', { hasText: /设置|Settings/ }).first().click()
await page.waitForTimeout(1500)
const url = page.url()
const nav = await page.locator('.set-nav-item').count()
console.log(`设置点击 → ${url} · settings nav items: ${nav}`)
await page.screenshot({ path: '/Users/phoebej/Develop/Java/FengYu/design-mockups/infinia-skin/settings-fixed.png' })
await browser.close()
