package fan.summer.api.ai;

import java.util.Collections;
import java.util.Map;
import java.util.concurrent.atomic.AtomicLong;

/**
 * An immutable record representing a single tool-call request generated by the AI model
 * during a chat completion.
 *
 * <p>Each tool call carries a unique ID, the tool's registered name, and a map of
 * argument name → value pairs. The inference engine resolves the corresponding
 * {@link AiTool}, invokes it, and feeds the result back as a {@link AiChatMessage}
 * with {@code role == TOOL}.</p>
 *
 * @param id        a unique call identifier (e.g. {@code "call_1718012345_0"})
 * @param name      the registered name of the tool to invoke
 * @param arguments the argument map; defensively copied into an unmodifiable map
 * @see AiTool
 * @see AiChatMessage#toolResult(String, String, String)
 */
public record AiToolCall(
    String id,
    String name,
    Map<String, Object> arguments
) {
    /** Compact constructor — defensively copies the arguments map. */
    public AiToolCall {
        arguments = arguments == null ? Collections.emptyMap() : Map.copyOf(arguments);
    }

    /**
     * Creates a new tool call with an auto-generated unique ID.
     *
     * @param name      the tool name
     * @param arguments the argument map (may be {@code null})
     * @return a new {@code AiToolCall} with a generated ID
     */
    public static AiToolCall of(String name, Map<String, Object> arguments) {
        return new AiToolCall(generateId(), name, arguments);
    }

    private static final AtomicLong counter = new AtomicLong(0);

    /** Generates a unique call ID combining timestamp and a monotonic counter. */
    private static String generateId() {
        return "call_" + System.currentTimeMillis() + "_" + counter.getAndIncrement();
    }
}