package fan.summer.api.ai;

import java.util.Collections;
import java.util.Map;

/**
 * Represents a tool call request generated by the AI model.
 */
public record AiToolCall(
    String id,
    String name,
    Map<String, Object> arguments
) {
    public AiToolCall {
        arguments = arguments == null ? Collections.emptyMap() : Map.copyOf(arguments);
    }

    public static AiToolCall of(String name, Map<String, Object> arguments) {
        return new AiToolCall(generateId(), name, arguments);
    }

    private static long counter = 0;
    private static String generateId() {
        return "call_" + System.currentTimeMillis() + "_" + (counter++);
    }
}