{
  "schemaVersion": 2,
  "id": "{{pluginId}}",
  "name": "{{pluginName}}",
  "description": "A FengYu plugin generated by @infinia/plugin-cli.",
  "version": "1.0.0",
  "author": "Plugin Author",
  "icon": "puzzle-outline",
  "category": "other",
  "ui": { "entry": "ui/index.html" },
  "backend": { "callTimeoutSeconds": 30 },
  "rpc": {
    "methods": {
      "hello": {
        "description": "Echo a greeting back to the UI.",
        "inputSchema": {
          "type": "object",
          "properties": { "name": { "type": "string", "description": "Name to greet." } },
          "required": ["name"]
        },
        "outputSchema": {
          "type": "object",
          "properties": { "message": { "type": "string" } },
          "required": ["message"]
        }
      }
    }
  },
  "permissions": [],
  "official": false,
  "aiTools": []
}
