package fan.summer.zhiflow.database.entity;

import lombok.Data;

/**
 * Entity representing a key-value application setting stored in the database.
 * <p>
 * Used for persisting arbitrary application configuration that can be dynamically
 * read and modified at runtime. Each setting is identified by a unique key.
 *
 * @since 3.0.0
 */
@Data
public class AppSettingEntity {
    /** Primary key, auto-generated by the database. */
    private Integer id;

    /** Unique identifier for the setting, used to look up values. */
    private String settingKey;

    /** The value associated with the setting key. */
    private String settingValue;
}
