package fan.summer.zhiflow.database.entity;

import lombok.Data;

/**
 * Entity for one plugin setting row: a key-value pair namespaced by plugin ID.
 *
 * @since 3.2.0
 */
@Data
public class PluginSettingEntity {
    /** Primary key, auto-generated by the database. */
    private Integer id;

    /** The owning plugin's ID ({@code SwissKitJPlugin.getId()}). */
    private String pluginId;

    /** The setting key, unique within one plugin. */
    private String settingKey;

    /** The setting value; may be null. */
    private String settingValue;
}
