{
  "schemaVersion": 1,
  "id": "{{pluginId}}",
  "name": "{{pluginName}}",
  "description": "A FengYu plugin generated by @infinia/plugin-cli.",
  "version": "1.0.0",
  "author": "",
  "icon": "puzzle-outline",
  "category": "other",
  "ui": { "entry": "ui/index.html" },
  "backend": { "command": "java -jar backend/worker.jar", "protocol": "json-rpc-2.0" },
  "permissions": [],
  "official": false,
  "aiTools": []
}
