package fan.summer.zhiflow.database.entity;

import lombok.Data;

import java.time.LocalDateTime;

/**
 * Entity representing a favorited (bookmarked) plugin stored in the database.
 *
 * <p>Each favorite is identified by the plugin's unique ID
 * ({@link fan.summer.zhiflow.api.SwissKitJPlugin#getId()}). Favorites are persisted
 * across application restarts and can be toggled from the tool card or detail panel.</p>
 *
 * @since 3.0.0
 */
@Data
public class PluginFavoriteEntity {
    /** Primary key, auto-generated by the database. */
    private Integer id;

    /** The unique plugin identifier this favorite references. */
    private String pluginId;

    /** Timestamp when this favorite was created. */
    private LocalDateTime createdAt;
}
