{
  "schemaVersion": 2,
  "id": "{{pluginId}}",
  "name": "{{pluginName}}",
  "description": "A FengYu Go plugin generated by @infinia/plugin-cli.",
  "version": "1.0.0",
  "engines": { "fengyu": ">=4.0.0-beta.4 <5.0.0" },
  "author": "Plugin Author",
  "icon": "puzzle-outline",
  "category": "other",
  "ui": { "entry": "ui/index.html" },
  "backend": { "runtime": "go", "protocolVersion": 1, "callTimeoutSeconds": 30 },
  "permissions": [],
  "official": false
}
