package fan.summer.database.entity.plugin;

import lombok.Data;
import java.sql.Timestamp;

/**
 * Entity representing a plugin managed by the built-in plugin manager.
 * <p>
 * Tracks plugin metadata including installation status, version information,
 * update URLs, and timestamps for last update check and installation.
 *
 * @since 3.0.0
 */
@Data
public class PluginManagerEntity {
    /** Primary key, auto-generated by the database. */
    private Integer id;

    /** Filename of the plugin JAR file in the plugins directory. */
    private String jarName;

    /** Display name of the plugin as defined in its manifest. */
    private String pluginName;

    /** Version string of the installed plugin. */
    private String pluginVersion;

    /** Whether the plugin is disabled; {@code 1} for disabled, {@code 0} for enabled. */
    private Integer isDisabled;

    /** URL to check for plugin updates. */
    private String updateUrl;

    /** Timestamp of the last update check. */
    private Timestamp lastCheck;

    /** Timestamp when the plugin was first installed. */
    private Timestamp installedAt;
}
