package fan.summer.database.entity.excel;

import lombok.Data;

/**
 * Entity representing a complex Excel split configuration for a specific task.
 * <p>
 * Each row defines how to split an Excel file: which sheet to process,
 * which row contains headers, and which column to group rows by.
 * Multiple configurations can exist for the same task to produce multiple output files.
 *
 * @since 3.0.0
 * @see fan.summer.database.mapper.excel.ComplexSplitConfigMapper
 */
@Data
public class ComplexSplitConfigEntity {
    /** Primary key, auto-generated by the database. */
    private Long id;

    /** Unique identifier for the split task this configuration belongs to. */
    private String taskId;

    /** Original filename of the Excel file being split. */
    private String fieldName;

    /** Name of the Excel sheet to split. */
    private String sheetName;

    /**
     * 1-based row index containing column headers.
     * Set to {@code -1} to indicate no header row (copy entire sheet).
     */
    private Integer headerIndex;

    /**
     * 1-based column index to split by (groups rows by unique values in this column).
     * Set to {@code -1} to indicate "copy all rows to every output file".
     */
    private Integer columnIndex;
}
