package fan.summer.fengyu.setup;

import fan.summer.fengyu.runtime.RuntimePaths;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.util.List;
import java.util.Properties;

/**
 * Reads/writes {@code datasource.properties} and assembles {@link DataSourceConfig} from
 * wizard params. Also handles password encryption via {@link CryptoUtil} and connection testing.
 *
 * <p>Config file location defaults to
 * {@code <programWorkingDirectory>/.fengyu/config/datasource.properties}. The runtime root is
 * injectable for testing.
 */
@Service
public class DataSourceConfigService {

    private static final Logger log = LoggerFactory.getLogger(DataSourceConfigService.class);

    private final Path baseDir;
    private final List<Path> legacyBaseDirs;

    /** Production constructor — uses {@code .fengyu} under the program working directory. */
    public DataSourceConfigService() {
        this(RuntimePaths.root(), List.of(
                Path.of(System.getProperty("user.dir")),
                Path.of(System.getProperty("user.home"), ".fengyu")));
    }

    /** Test constructor — injects base dir (temp dir). */
    public DataSourceConfigService(String baseDir) {
        this(Path.of(baseDir), List.of());
    }

    DataSourceConfigService(Path baseDir, Path legacyBaseDir) {
        this(baseDir, legacyBaseDir == null ? List.of() : List.of(legacyBaseDir));
    }

    DataSourceConfigService(Path baseDir, List<Path> legacyBaseDirs) {
        this.baseDir = baseDir.toAbsolutePath().normalize();
        this.legacyBaseDirs = legacyBaseDirs.stream()
                .map(path -> path.toAbsolutePath().normalize())
                .distinct()
                .toList();
    }

    private Path configFile() {
        return baseDir.resolve("config").resolve("datasource.properties");
    }

    /** The program-default embedded data-file path: {@code <baseDir>/database/fengyu}. */
    public Path defaultEmbeddedPath() {
        return baseDir.resolve("database").resolve("fengyu");
    }

    /** Loads the datasource config. Returns {@code null} if the file is missing or invalid. */
    public DataSourceConfig load() {
        migrateLegacyConfigIfNeeded();
        Path file = configFile();
        if (!Files.exists(file)) return null;
        try (InputStream in = Files.newInputStream(file)) {
            SensitiveFilePermissions.protectDirectory(file.getParent());
            SensitiveFilePermissions.protectFile(file);
            Properties props = new Properties();
            props.load(in);
            String typeStr = props.getProperty("db.type");
            if (typeStr == null || typeStr.isBlank()) return null;
            DbType type = DbType.fromName(typeStr);
            return new DataSourceConfig(
                    type,
                    props.getProperty("db.url"),
                    props.getProperty("db.driver"),
                    props.getProperty("db.dialect"),
                    props.getProperty("db.username", ""),
                    CryptoUtil.decrypt(props.getProperty("db.password", ""), machineIdFile()),
                    props.getProperty("db.file.path", ""));
        } catch (Exception e) {
            log.warn("Failed to load datasource.properties: {}", e.getMessage());
            return null;
        }
    }

    /** Persists the config, encrypting the password. */
    public void save(DataSourceConfig cfg) {
        try {
            Path file = configFile();
            Files.createDirectories(file.getParent());
            SensitiveFilePermissions.protectDirectory(file.getParent());
            Properties props = new Properties();
            props.setProperty("db.type", cfg.type().name().toLowerCase());
            props.setProperty("db.url", cfg.url());
            props.setProperty("db.driver", cfg.driver());
            props.setProperty("db.dialect", cfg.dialect());
            if (cfg.username() != null) props.setProperty("db.username", cfg.username());
            if (cfg.password() != null && !cfg.password().isBlank()) {
                props.setProperty("db.password", CryptoUtil.encrypt(cfg.password(), machineIdFile()));
            }
            if (cfg.filePath() != null) props.setProperty("db.file.path", cfg.filePath());
            try (OutputStream out = Files.newOutputStream(file)) {
                props.store(out, "FengYu datasource configuration (generated by setup wizard)");
            }
            SensitiveFilePermissions.protectFile(file);
            log.info("Saved datasource.properties: type={}", cfg.type());
        } catch (IOException e) {
            throw new RuntimeException("Failed to write datasource.properties", e);
        }
    }

    /**
     * Backs up and clears {@code datasource.properties}: moves it to
     * {@code datasource.properties.bak} (or {@code .bak.<millis>} if a {@code .bak} already
     * exists, to avoid clobbering a prior backup). If the move fails, falls back to a direct
     * delete. Returns the backup path, or {@code null} if there was no file or backup/delete
     * failed entirely. Never throws — callers (startup probe, reset endpoints) rely on this to
     * degrade gracefully so the app can still boot into SETUP mode.
     */
    public Path backupAndClear() {
        Path file = configFile();
        if (!Files.exists(file)) return null;
        Path bak = file.resolveSibling(file.getFileName() + ".bak");
        if (Files.exists(bak)) {
            bak = file.resolveSibling(file.getFileName() + ".bak." + System.currentTimeMillis());
        }
        try {
            Files.move(file, bak);
            log.warn("Backed up stale datasource.properties to {}", bak);
            return bak;
        } catch (IOException moveErr) {
            log.warn("Move to .bak failed ({}); attempting direct delete", moveErr.getMessage());
            try {
                Files.deleteIfExists(file);
                log.warn("Deleted datasource.properties directly (backup unavailable)");
            } catch (IOException delErr) {
                log.error("Could not backup or delete datasource.properties: {}", delErr.getMessage());
            }
            return null;
        }
    }

    /**
     * Assembles a {@link DataSourceConfig} from wizard params, resolving paths/URL. For embedded
     * databases (H2/SQLite) the parent directory of the data file is created here so the JDBC
     * driver can initialize the database file on first connection — without this the connection
     * test fails because the target directory does not exist. Does NOT persist the config —
     * call {@link #save} after testing.
     */
    public DataSourceConfig buildFromWizard(DbType type, WizardParams params) {
        String url;
        String filePath = null;
        if (type.embedded) {
            // Default data file lives under <programWorkingDirectory>/.fengyu/database/fengyu.
            String rawPath = (params.filePath() == null || params.filePath().isBlank())
                    ? defaultEmbeddedPath().toString()
                    : params.filePath();
            Path resolved = Path.of(rawPath);
            if (!resolved.isAbsolute()) {
                resolved = baseDir.resolve(rawPath).toAbsolutePath();
            }
            // Ensure the parent directory exists — the JDBC driver creates the file itself, but
            // only if its directory is already present (H2/SQLite both fail otherwise).
            Path parent = resolved.getParent();
            if (parent != null) {
                try {
                    Files.createDirectories(parent);
                } catch (IOException e) {
                    throw new IllegalStateException(
                            "Failed to create database directory " + parent + ": " + e.getMessage(), e);
                }
            }
            filePath = resolved.toString().replace("\\", "/");
            url = type.urlTemplate.replace("{path}", filePath);
        } else {
            int port = params.port() != null ? params.port() : defaultPort(type);
            url = type.urlTemplate
                    .replace("{host}", params.host())
                    .replace("{port}", String.valueOf(port))
                    .replace("{db}", params.database());
        }
        return new DataSourceConfig(
                type, url, type.driver, type.dialect,
                params.username() == null ? "" : params.username(),
                params.password() == null ? "" : params.password(),
                filePath);
    }

    private int defaultPort(DbType type) {
        return switch (type) {
            case MYSQL -> 3306;
            case POSTGRESQL -> 5432;
            default -> 0;
        };
    }

    /**
     * Tests a connection WITHOUT persisting. Opens a raw JDBC connection (3s timeout),
     * runs {@code SELECT 1}, returns metadata. Connection is always closed.
     */
    public ConnectionTestResult testConnection(DataSourceConfig cfg) {
        try {
            Class.forName(cfg.driver());
        } catch (ClassNotFoundException e) {
            return ConnectionTestResult.fail("Driver not found: " + cfg.driver());
        }
        String sql = "SELECT 1";
        // SQLite uses a different validation query syntax but SELECT 1 works on all four.
        try (Connection conn = DriverManager.getConnection(cfg.url(),
                cfg.username().isBlank() ? null : cfg.username(),
                cfg.password().isBlank() ? null : cfg.password())) {
            conn.createStatement().execute(sql);
            DatabaseMetaData md = conn.getMetaData();
            return ConnectionTestResult.ok(cfg.dialect(),
                    md.getDatabaseProductName() + " " + md.getDatabaseProductVersion());
        } catch (Exception e) {
            return ConnectionTestResult.fail(e.getMessage());
        }
    }

    /** Decrypts the password field (load() already decrypts; this is for explicitness). */
    public String decryptPassword(DataSourceConfig cfg) {
        return CryptoUtil.decrypt(cfg.password(), machineIdFile());
    }

    private Path machineIdFile() {
        return baseDir.resolve("config").resolve(".machineid");
    }

    /**
     * One-time compatibility bridge for builds that stored setup state directly under the
     * working directory or under {@code user.home/.fengyu}. Copying (rather than moving) keeps
     * the old installation recoverable.
     */
    private void migrateLegacyConfigIfNeeded() {
        if (Files.exists(configFile())) return;
        for (Path legacyBaseDir : legacyBaseDirs) {
            if (!legacyBaseDir.equals(baseDir) && migrateLegacyConfig(legacyBaseDir)) {
                return;
            }
        }
    }

    private boolean migrateLegacyConfig(Path legacyBaseDir) {
        Path legacyConfig = legacyBaseDir.resolve("config").resolve("datasource.properties");
        if (!Files.isRegularFile(legacyConfig)) return false;
        try {
            Files.createDirectories(configFile().getParent());
            Path legacyMachineId = legacyBaseDir.resolve("config").resolve(".machineid");
            if (Files.isRegularFile(legacyMachineId) && !Files.exists(machineIdFile())) {
                Files.copy(legacyMachineId, machineIdFile());
                SensitiveFilePermissions.protectFile(machineIdFile());
            }
            Files.copy(legacyConfig, configFile());
            SensitiveFilePermissions.protectDirectory(configFile().getParent());
            SensitiveFilePermissions.protectFile(configFile());
            log.info("Migrated datasource configuration from legacy runtime directory {}", legacyBaseDir);
            return true;
        } catch (java.nio.file.FileAlreadyExistsException ignored) {
            // Another startup process completed the same migration.
            return true;
        } catch (IOException e) {
            log.warn("Could not migrate legacy datasource configuration: {}", e.getMessage());
            return false;
        }
    }

    /** Test-only: read raw properties (with encrypted password) for assertions. */
    Properties readRawForTest() throws IOException {
        Properties props = new Properties();
        try (InputStream in = Files.newInputStream(configFile())) {
            props.load(in);
        }
        return props;
    }

    /** Test-only: the config file path (for existence assertions). Public so tests in
     *  other packages (e.g. {@code fan.summer.fengyu.HeadlessLauncherProbeTest}) can assert
     *  on the config file without duplicating path logic. */
    public Path configFileForTest() {
        return configFile();
    }
}
