package fan.summer.database.entity.email;

import lombok.Data;

import java.util.Date;

/**
 * Entity representing an archived email message stored in the local database.
 *
 * <p>Each record captures metadata (sender, recipients, subject, date) and a reference
 * to the archived {@code .eml} file on disk. Records are keyed by the combination of
 * {@code accountEmail + folder + messageUid} to prevent duplicates.</p>
 *
 * @since 3.0.0
 */
@Data
public class EmailArchiveEntity {
    /** Primary key, auto-generated by the database. */
    private Integer id;
    /** The email account address that received or sent this message. */
    private String accountEmail;
    /** The IMAP folder the message was archived from (e.g. "INBOX", "Sent"). */
    private String folder;
    /** The unique IMAP message UID within the folder. */
    private String messageUid;
    /** The email subject line. */
    private String subject;
    /** The sender's email address. */
    private String fromAddress;
    /** The recipient email addresses (comma-separated). */
    private String toAddress;
    /** The CC recipient email addresses (comma-separated). */
    private String ccAddress;
    /** The date the email was originally sent. */
    private Date sendDate;
    /** Whether the email has at least one attachment. */
    private Boolean hasAttachment;
    /** The local filesystem path to the archived {@code .eml} file. */
    private String emlPath;
    /** A short text preview of the email body (truncated). */
    private String bodyPreview;
    /** The timestamp when this email was archived locally. */
    private Date archivedAt;
}
