package fan.summer.zhiflow.database.entity.email;

import lombok.Data;

import java.util.Date;

/**
 * Entity representing a log entry for a sent email.
 * <p>
 * Records the details of each email send operation, including recipients,
 * subject, content, attachments, send timestamp, and success status.
 *
 * @since 3.0.0
 */
@Data
public class EmailSentLogEntity {
    /** Primary key, auto-generated by the database. */
    private Long id;

    /** Primary recipient email addresses, comma-separated if multiple. */
    private String to;

    /** CC recipient email addresses, comma-separated if multiple. */
    private String cc;

    /** BCC recipient email addresses, comma-separated if multiple. */
    private String bcc;

    /** Subject line of the sent email. */
    private String subject;

    /** HTML or plain-text body content of the email. */
    private String content;

    /** File paths of attachments, typically comma-separated. */
    private String attachment;

    /** Timestamp when the email was sent. */
    private Date sendTime;

    /** Whether the send operation completed successfully. */
    private boolean isSuccess;
}
