/**
 * Deterministic contract generator for FengYu plugin manifests (schema v2).
 *
 * Reads a manifest's `rpc.methods` table and emits:
 *   - TypeScript: a typed RPC client (input/output interfaces + createPluginRpc)
 *     at <ui-root>/src/generated/fengyu-rpc.ts
 *   - Java: per-method Input/Output records + a centralized PluginMethods name
 *     class at <worker-root>/src/main/java/<id-as-package>/generated/
 *
 * Output is a pure function of the manifest (methods and properties are emitted in
 * sorted order), so two consecutive runs produce byte-for-byte identical files.
 * The generator is reused by `fengyu init|dev|build` (write) and `fengyu check`
 * (drift detection only — it never writes).
 *
 * Unsupported JSON-Schema constructs are rejected with a precise error rather than
 * coerced to a generic type, so a manifest that drifts from the supported subset
 * (object/array/string/integer/number/boolean + enum/required/nullable) fails the
 * build instead of producing a silently wrong client.
 */
import fs from 'node:fs/promises'
import path from 'node:path'

import { readManifest } from './manifest.mjs'

const TS_HEADER = '// Generated by FengYu Toolchain. Do not edit.'
const JAVA_HEADER = '// Generated by FengYu Toolchain. Do not edit.'

const TS_IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/
const JAVA_RESERVED = new Set([
  'abstract', 'assert', 'boolean', 'break', 'byte', 'case', 'catch', 'char', 'class',
  'const', 'continue', 'default', 'do', 'double', 'else', 'enum', 'extends', 'final',
  'finally', 'float', 'for', 'goto', 'if', 'implements', 'import', 'instanceof', 'int',
  'interface', 'long', 'native', 'new', 'package', 'private', 'protected', 'public',
  'return', 'short', 'static', 'strictfp', 'super', 'switch', 'synchronized', 'this',
  'throw', 'throws', 'transient', 'try', 'void', 'volatile', 'while', 'true', 'false',
  'null', 'var', 'yield', 'record', 'sealed', 'permits',
])

const SUPPORTED_TYPES = new Set(['object', 'array', 'string', 'integer', 'number', 'boolean'])

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/** Method/field name → PascalCase type prefix: render → Render, splitStart → SplitStart,
 *  excel_complex_config → ExcelComplexConfig (splits on underscores, not just the first letter). */
function pascal(name) {
  if (!name) return name
  return name.split(/_+/).filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1)).join('')
}

/** Sorted [name, method] pairs from rpc.methods, so output never depends on key order. */
function sortedMethods(manifest) {
  const methods = manifest.rpc?.methods ?? {}
  return Object.keys(methods).sort().map((name) => [name, methods[name]])
}

/** True if the manifest has any RPC methods to generate code for. */
export function hasRpc(manifest) {
  return Object.keys(manifest.rpc?.methods ?? {}).length > 0
}

/** Derive the Java base package from the plugin id (mirrors create.mjs), e.g. fan.summer.markdown. */
export function javaBasePackage(id) {
  return id.split('.').map((part) => part.replace(/-/g, '_')).join('.')
}

/** A JSON property key rendered as a TS object-type key, quoting non-identifiers. */
function tsKey(name) {
  return TS_IDENT.test(name) ? name : JSON.stringify(name)
}

/** A single-quoted TS string literal (matches SDK style; JSON.stringify uses double quotes). */
function tsStr(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

/** A JSON property key rendered as a safe Java identifier (reserved words get a trailing _). */
function javaIdent(name) {
  let s = String(name).replace(/[^A-Za-z0-9_]/g, '_')
  if (/^[0-9]/.test(s)) s = '_' + s
  if (JAVA_RESERVED.has(s)) s = s + '_'
  return s
}

function assertSupported(schema, where) {
  if (!schema || typeof schema !== 'object') {
    throw new Error(`${where}: schema must be an object`)
  }
  if (!SUPPORTED_TYPES.has(schema.type)) {
    throw new Error(`${where}: unsupported schema type ${JSON.stringify(schema.type)} (supported: ${[...SUPPORTED_TYPES].join(', ')})`)
  }
}

// ---------------------------------------------------------------------------
// TypeScript
// ---------------------------------------------------------------------------

function tsType(schema, where) {
  assertSupported(schema, where)
  let base
  switch (schema.type) {
    case 'string':
      base = Array.isArray(schema.enum) && schema.enum.length
        ? schema.enum.map((v) => JSON.stringify(String(v))).join(' | ')
        : 'string'
      break
    case 'integer':
    case 'number':
      base = 'number'
      break
    case 'boolean':
      base = 'boolean'
      break
    case 'array': {
      const inner = tsType(schema.items ?? {}, `${where}.items`)
      base = inner.includes(' | ') ? `(${inner})[]` : `${inner}[]`
      break
    }
    case 'object':
      base = tsInlineObject(schema, where)
      break
    default:
      base = 'unknown'
  }
  return schema.nullable === true ? `${base} | null` : base
}

function tsInlineObject(schema, where) {
  const props = schema.properties ?? {}
  const required = new Set(schema.required ?? [])
  const entries = Object.keys(props).sort().map((k) => {
    const opt = required.has(k) ? '' : '?'
    return `${tsKey(k)}${opt}: ${tsType(props[k], `${where}.${k}`)}`
  })
  return `{ ${entries.join('; ')} }`
}

function tsTypeAlias(name, schema, where) {
  const props = schema.properties ?? {}
  const required = new Set(schema.required ?? [])
  const lines = Object.keys(props).sort().map((k) => {
    const opt = required.has(k) ? '' : '?'
    return `  ${tsKey(k)}${opt}: ${tsType(props[k], `${where}.${k}`)}`
  })
  const body = lines.length ? `\n${lines.join('\n')}\n` : ''
  // Emit a `type` alias (not an `interface`): the generated client passes these values to
  // FengYuClient.invoke(method, params: Record<string, unknown>). TypeScript does NOT give
  // interfaces an implicit index signature, so an interface-typed argument fails with TS2345;
  // an object type alias is assignable to Record<string, unknown>.
  return `export type ${name} = {${body}}`
}

/** Generate the full fengyu-rpc.ts source for a manifest (null when there are no RPC methods). */
export function generateTypescript(manifest) {
  const methods = sortedMethods(manifest)
  if (methods.length === 0) return null
  const out = [TS_HEADER, '', "import type { FengYuClient, InvokeOptions } from '@infinia/plugin-sdk'", '']

  const ifaceBlocks = []
  const rpcMembers = []
  const createLines = []
  for (const [name, method] of methods) {
    const inName = `${pascal(name)}Input`
    ifaceBlocks.push(tsTypeAlias(inName, method.inputSchema, `rpc.methods.${name}.inputSchema`))
    let outName = 'unknown'
    if (method.outputSchema) {
      outName = `${pascal(name)}Output`
      ifaceBlocks.push(tsTypeAlias(outName, method.outputSchema, `rpc.methods.${name}.outputSchema`))
    }
    rpcMembers.push(`  ${name}(input: ${inName}, options?: InvokeOptions): Promise<${outName}>`)
    createLines.push(`    ${name}: (input, options) => client.invoke<${outName}>(${tsStr(name)}, input, options),`)
  }

  out.push(ifaceBlocks.join('\n\n'), '')
  out.push('export interface PluginRpc {', rpcMembers.join('\n'), '}', '')
  out.push('export function createPluginRpc(client: FengYuClient): PluginRpc {')
  out.push('  return {')
  out.push(...createLines)
  out.push('  }', '}', '')
  return out.join('\n')
}

// ---------------------------------------------------------------------------
// Java
// ---------------------------------------------------------------------------

function indent(text, pad) {
  return text.split('\n').map((l) => (l.length ? pad + l : l)).join('\n')
}

/**
 * Java field type + nested-record declarations for a schema. Object-typed fields (and the items
 * of an array-of-objects) produce a nested static record named `<ownerRecord><Pascal(field)>`
 * (e.g. field `rows` in `AnalyzeOutput` → `AnalyzeOutputRows`), declared inside the owning record
 * body. Naming keys off the field name (not the literal "items") so two array-of-object fields in
 * the same record cannot collide.
 *
 * @param fieldName the immediately-enclosing field name, used to name nested records
 * @returns {{ type: string, nested?: string }} where `nested` is a complete record body to inline
 */
function javaFieldType(schema, where, required, ownerRecordName, fieldName) {
  assertSupported(schema, where)
  const nullable = schema.nullable === true
  const primitive = required && !nullable
  switch (schema.type) {
    case 'string': {
      // A closed enum (all values valid Java identifiers, none reserved) becomes a real Java enum
      // nested in the owning record. The constant name IS the wire value, so Enum.name(),
      // toString(), and String.valueOf(enum) all return the wire value — Gson round-trips it
      // exactly with no @SerializedName, and worker code that bridges the enum into a legacy
      // Map (String.valueOf(map.get(field))) keeps seeing the wire value. A value that is not a
      // valid Java identifier (or is reserved) falls back to String rather than aliasing it.
      if (Array.isArray(schema.enum) && schema.enum.length && schema.enum.every(isValidJavaEnumConstant)) {
        const enumName = `${ownerRecordName}${pascal(fieldName)}`
        return { type: enumName, nested: javaEnum(enumName, schema.enum) }
      }
      return { type: 'String' }
    }
    case 'integer': return { type: primitive ? 'int' : 'Integer' }
    case 'number': return { type: primitive ? 'double' : 'Double' }
    case 'boolean': return { type: primitive ? 'boolean' : 'Boolean' }
    case 'array': {
      // Pass the SAME fieldName down so an array-of-objects names its item record after the field
      // (e.g. `rows` → OwnerRows), and propagate the nested declaration so it is actually emitted.
      const inner = javaFieldType(schema.items ?? {}, `${where}.items`, false, ownerRecordName, fieldName)
      const result = { type: `List<${inner.type}>` }
      if (inner.nested) result.nested = inner.nested
      return result
    }
    case 'object': {
      const nestedName = `${ownerRecordName}${pascal(fieldName)}`
      return { type: nestedName, nested: javaRecord(nestedName, schema, where) }
    }
    default:
      throw new Error(`${where}: unsupported schema type ${JSON.stringify(schema.type)}`)
  }
}

/** True when `v` is a valid Java enum constant name equal to its own wire value (so name()
 *  round-trips with no aliasing): a valid identifier and not a Java reserved word. */
function isValidJavaEnumConstant(v) {
  const s = String(v)
  return TS_IDENT.test(s) && !JAVA_RESERVED.has(s)
}

/** A nested Java enum whose constants are exactly the schema enum values (== wire values). */
function javaEnum(name, values) {
  const constants = values.map((v) => `  ${String(v)}`).join(',\n')
  return `public enum ${name} {\n${constants}\n}`
}

/** Emit a Java record (with nested static records for object-typed fields). */
function javaRecord(recordName, schema, where) {
  assertSupported(schema, where)
  const props = schema.properties ?? {}
  const required = new Set(schema.required ?? [])
  const fields = []
  const nestedDecls = []
  for (const fname of Object.keys(props).sort()) {
    const ft = javaFieldType(props[fname], `${where}.${fname}`, required.has(fname), recordName, fname)
    fields.push(`    @SerializedName(${JSON.stringify(fname)}) ${ft.type} ${javaIdent(fname)}`)
    if (ft.nested) nestedDecls.push(ft.nested)
  }
  const header = fields.length === 0
    ? `public record ${recordName}()`
    : `public record ${recordName}(\n${fields.join(',\n')}\n)`
  if (nestedDecls.length === 0) return `${header} {}`
  return `${header} {\n${nestedDecls.map((b) => indent(b, '  ')).join('\n\n')}\n}`
}

/** Assemble a .java file with the package decl + only the imports the body uses. */
function javaFile(packageName, body) {
  const imports = []
  if (body.includes('@SerializedName')) imports.push('com.google.gson.annotations.SerializedName')
  if (body.includes('List<')) imports.push('java.util.List')
  const importBlock = imports.length ? [...imports.map((i) => `import ${i};`), ''].join('\n') : ''
  return [JAVA_HEADER, `package ${packageName};`, '', importBlock, body, '']
    .filter((l, i, arr) => !(l === '' && arr[i - 1] === ''))
    .join('\n')
}

/** Method name → SCREAMING_SNAKE constant: render → RENDER, splitStart → SPLIT_START. */
function javaConst(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase()
}

/**
 * Generate the Java file set for a manifest. Returns an array of
 * { name: <simple file name>, content } in sorted order.
 */
export function generateJava(manifest) {
  const methods = sortedMethods(manifest)
  if (methods.length === 0) return []
  const pkg = `${javaBasePackage(manifest.id)}.generated`
  const files = []

  const constants = methods.map(([name]) => `  public static final String ${javaConst(name)} = ${JSON.stringify(name)};`)
  const methodsBody = `public final class PluginMethods {\n  private PluginMethods() {}\n\n${constants.join('\n')}\n}`
  files.push({ name: 'PluginMethods.java', content: javaFile(pkg, methodsBody) })

  for (const [name, method] of methods) {
    const inName = `${pascal(name)}Input`
    files.push({ name: `${inName}.java`, content: javaFile(pkg, javaRecord(inName, method.inputSchema, `rpc.methods.${name}.inputSchema`)) })
    if (method.outputSchema) {
      const outName = `${pascal(name)}Output`
      files.push({ name: `${outName}.java`, content: javaFile(pkg, javaRecord(outName, method.outputSchema, `rpc.methods.${name}.outputSchema`)) })
    }
  }
  files.sort((a, b) => a.name.localeCompare(b.name))
  return files
}

// ---------------------------------------------------------------------------
// Project-resolved generation (write + drift check)
// ---------------------------------------------------------------------------

/**
 * Compute the absolute paths + expected contents of every generated file for a
 * project. Pure: reads only the manifest + project model, writes nothing.
 *
 * @param {{ root: string, config: object }} project - result of detectProject
 * @param {object} manifest - parsed manifest
 * @returns {{ path: string, content: string }[]}
 */
export function generatedFilesFor(project, manifest) {
  const out = []
  if (!hasRpc(manifest)) return out
  const uiRoot = project.config?.ui?.root
  if (uiRoot) {
    const ts = generateTypescript(manifest)
    if (ts) out.push({ path: path.join(uiRoot, 'src', 'generated', 'fengyu-rpc.ts'), content: ts })
  }
  const workerRoot = project.config?.worker?.root
  if (workerRoot) {
    const pkgPath = javaBasePackage(manifest.id).replace(/\./g, path.sep)
    const genDir = path.join(workerRoot, 'src', 'main', 'java', pkgPath, 'generated')
    for (const f of generateJava(manifest)) {
      out.push({ path: path.join(genDir, f.name), content: f.content })
    }
  }
  return out
}

/**
 * Write generated files for a project (used by init/dev/build). Creates parent
 * directories. Returns the list of written absolute paths.
 */
export async function writeGenerated(project, manifest) {
  const files = generatedFilesFor(project, manifest)
  for (const f of files) {
    await fs.mkdir(path.dirname(f.path), { recursive: true })
    await fs.writeFile(f.path, f.content, 'utf8')
  }
  return files.map((f) => f.path)
}

/**
 * Drift check (used by `fengyu check`). Compares expected generated content to
 * the on-disk files WITHOUT writing. Returns a list of error messages (empty
 * when every expected file is present and up-to-date).
 *
 * @param {{ root: string, config: object }} project
 * @param {object} manifest
 * @returns {Promise<string[]>}
 */
export async function checkDrift(project, manifest) {
  const errors = []
  const expected = generatedFilesFor(project, manifest)
  for (const f of expected) {
    let actual
    try {
      actual = await fs.readFile(f.path, 'utf8')
    } catch {
      errors.push(`generated file is missing — run \`fengyu build\` (or \`fengyu dev\`): ${path.relative(project.root, f.path)}`)
      continue
    }
    if (actual !== f.content) {
      errors.push(`generated file is stale — regenerate it: ${path.relative(project.root, f.path)}`)
    }
  }
  return errors
}

/** Convenience: read a project's manifest + detect drift in one call. */
export async function checkProjectGenerated(project) {
  const manifest = await readManifest(project.root)
  return checkDrift(project, manifest)
}
