package fan.summer.database.entity.setting.email;

import lombok.Data;

/**
 * Entity representing an entry in the email address book.
 * <p>
 * Stores saved email addresses with optional nicknames and tags for
 * easier recipient selection during email composition.
 *
 * @since 3.0.0
 */
@Data
public class EmailAddressBookEntity {
    /** Primary key, auto-generated by the database. */
    private Integer id;

    /** Email address string (e.g., {@code user@example.com}). */
    private String emailAddress;

    /** Optional friendly name or alias for the email address. */
    private String nickname;

    /** Comma-separated list of tags associated with this address. */
    private String tags;
}
