package fan.summer.database.entity.setting.email;

import lombok.Data;

/**
 * Entity representing the email SMTP configuration for the application.
 * <p>
 * Stores the SMTP server settings used for sending emails, including
 * server address, port, authentication credentials, and security protocols.
 *
 * @since 3.0.0
 */
@Data
public class SwissKitSettingEmailEntity {
    /** Primary key, auto-generated by the database. */
    private Integer id;

    /** SMTP authentication email address. */
    private String email;

    /** SMTP authentication password or app-specific password. */
    private String password;

    /** SMTP server hostname or IP address. */
    private String smtpAddress;

    /** SMTP server port number (e.g., {@code 587} for TLS, {@code 465} for SSL). */
    private Integer smtpPort;

    /** Whether STARTTLS is required for the connection. */
    private Boolean needTLS;

    /** Whether SSL/TLS is required for the connection. */
    private Boolean needSSL;

    /** The "From" address displayed in sent emails. */
    private String fromAddress;
}
