<script setup lang="ts">
import { ref } from 'vue'
import { useAccountsStore } from '../stores/accounts'
import { useComposeStore } from '../stores/compose'
import { useContactsStore } from '../stores/contacts'
import { actionable, files, invoke } from '../sdk'
const accounts = useAccountsStore(), contacts = useContactsStore(), compose = useComposeStore()
const mode = ref<'TAGS'|'FILENAME'>('TAGS'), directory = ref<{id:string;name:string}|null>(null), dialog = ref(false), error = ref('')
async function chooseDirectory() { try { directory.value = await files.inputDirectory() } catch(value){error.value=actionable(value,'Selecting batch directory')} }
async function prepare() { try { const result = await invoke<{confirmation:{confirmationId:string;summary:{label:string;value:string}[];expiresAt:string}}>('email_send_batch', { mode: mode.value, accountId: accounts.selectedId, tagIds: contacts.selectedTagIds, inputDirectory: directory.value, subject: compose.subject, plainText: compose.plainText, htmlText: compose.htmlText }); compose.setConfirmation(result.confirmation); dialog.value=true } catch(value){ error.value=actionable(value,'Preparing batch') } }
async function confirm(){ if(!compose.confirmation)return;try{const result=await invoke<{send:{status:string;succeeded:number;failed:number;failedRecipients:string[]}}>('confirm_send',{confirmationId:compose.confirmation.confirmationId});compose.sendResult=result.send;dialog.value=false}catch(value){error.value=actionable(value,'Sending batch')}}
async function reject(){if(!compose.confirmation)return;try{await invoke('reject_send',{confirmationId:compose.confirmation.confirmationId});dialog.value=false}catch(value){error.value=actionable(value,'Cancelling batch')}}
</script>
<template><v-card class="surface" variant="flat"><v-card-title>Batch send</v-card-title><v-card-text><v-alert v-if="error" type="error" class="mb-4">{{error}}</v-alert><v-btn-toggle v-model="mode" mandatory color="primary"><v-btn value="TAGS">Address-book tags</v-btn><v-btn value="FILENAME">Filename suffix</v-btn></v-btn-toggle>
<template v-if="mode==='TAGS'"><v-select v-model="contacts.selectedTagIds" :items="contacts.tags" item-title="name" item-value="id" label="Recipient tags" multiple chips/><p class="hint">{{contacts.recipientPreview.length}} resolved recipients: {{contacts.recipientPreview.join(', ')||'select tags to preview'}}</p></template>
<template v-else><v-btn prepend-icon="mdi-folder-open" variant="tonal" @click="chooseDirectory">Choose attachment directory</v-btn><p class="hint">{{directory?.name||'Recipients are derived from the suffix after the last underscore; the exact count is shown in the confirmation preview.'}}</p></template>
<v-text-field v-model="compose.subject" label="Subject template"/><v-textarea v-model="compose.plainText" label="Message template"/></v-card-text><v-card-actions><v-spacer/><v-btn color="primary" @click="prepare">Review batch</v-btn></v-card-actions></v-card>
<v-alert v-if="compose.sendResult" :type="compose.sendResult.failed?'warning':'success'" class="mt-4">Processed {{compose.sendResult.succeeded+compose.sendResult.failed}} · succeeded {{compose.sendResult.succeeded}} · failed {{compose.sendResult.failed}}</v-alert><v-dialog v-model="dialog" max-width="560" persistent><v-card><v-card-title>Confirm batch</v-card-title><v-card-text><v-list density="compact"><v-list-item v-for="row in compose.confirmation?.summary" :key="row.label" :title="row.label" :subtitle="row.value"/></v-list></v-card-text><v-card-actions><v-spacer/><v-btn @click="reject">Reject</v-btn><v-btn color="primary" @click="confirm">Confirm batch</v-btn></v-card-actions></v-card></v-dialog></template>
