<script setup lang="ts">
import { ref } from 'vue'
import { useAccountsStore } from '../stores/accounts'
import { useArchiveStore } from '../stores/archive'
import { actionable, files, invoke } from '../sdk'
const accounts=useAccountsStore(), archive=useArchiveStore(), folder=ref('INBOX'), start=ref(''), end=ref(''), output=ref<{id:string;name:string}|null>(null), busy=ref(false), error=ref(''), summary=ref('')
async function choose(){try{output.value=await files.outputDirectory()}catch(value){error.value=actionable(value,'Selecting output directory')}}
const instant = (value: string) => value ? new Date(value).toISOString() : undefined
async function collect(){busy.value=true;try{const result=await invoke<{collection:{newArchived:number;skippedDuplicates:number;failures:number}}>('email_archive_fetch',{accountId:accounts.selectedId,folder:folder.value,start:instant(start.value),end:instant(end.value),outputDirectory:output.value});summary.value=result.summary;archive.updateProgress({processed:result.collection.newArchived+result.collection.skippedDuplicates+result.collection.failures,newArchived:result.collection.newArchived,duplicates:result.collection.skippedDuplicates,failed:result.collection.failures,successful:result.collection.newArchived})}catch(value){error.value=actionable(value,'Collecting mail')}finally{busy.value=false}}
</script>
<template><v-card class="surface" variant="flat"><v-card-title>Collect mail</v-card-title><v-card-text><v-alert v-if="error" type="error" class="mb-4">{{error}}</v-alert><v-alert v-if="summary" type="success" class="mb-4">{{summary}}</v-alert><v-select v-model="accounts.selectedId" :items="accounts.accounts" item-title="email" item-value="id" label="IMAP account"/><v-text-field v-model="folder" label="Folder"/><div class="inline-fields"><v-text-field v-model="start" type="datetime-local" label="From"/><v-text-field v-model="end" type="datetime-local" label="To"/></div><v-btn variant="tonal" @click="choose">{{output?.name||'Choose output directory'}}</v-btn><div class="progress-grid"><span>Processed {{archive.progress.processed}}</span><span>New {{archive.progress.newArchived}}</span><span>Duplicates {{archive.progress.duplicates}}</span><span>Failed {{archive.progress.failed}}</span></div></v-card-text><v-card-actions><v-spacer/><v-btn color="primary" :loading="busy" :disabled="!output||!accounts.selectedId" @click="collect">Collect now</v-btn></v-card-actions></v-card></template>
