<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useAccountsStore } from '../stores/accounts'
import { useArchiveStore } from '../stores/archive'
import { actionable, invoke } from '../sdk'
const accounts=useAccountsStore(), archive=useArchiveStore(), view=ref<'records'|'accounts'>('records'), recordKind=ref<'archive'|'send'>('archive'), error=ref(''), detail=ref<Record<string,unknown>>(), confirmationId=ref(''), sendRecord=ref<Record<string,unknown>>(), failedRecipients=ref<string[]>([])
async function guard(action:string,task:()=>Promise<void>){try{error.value='';await task()}catch(value){error.value=actionable(value,action)}}
const loadArchive=()=>guard('Loading archive',async()=>{const result=await invoke<{messages:Record<string,unknown>[]}>('email_archive_query',{offset:archive.offset,limit:archive.limit});archive.messages=result.messages??[]})
const openDetail=(id:unknown)=>guard('Loading message detail',async()=>{const result=await invoke<{message:Record<string,unknown>}>('email_archive_detail',{id});detail.value=result.message})
const lookupSend=()=>guard('Loading send status',async()=>{const result=await invoke<{send:Record<string,unknown>}>('email_send_status',{confirmationId:confirmationId.value});sendRecord.value=result.send;failedRecipients.value=(result.send.failedRecipients as string[])??[]})
const retry=()=>guard('Preparing retry',async()=>{const result=await invoke<{confirmation:{confirmationId:string}}>('email_send_retry',{confirmationId:confirmationId.value,failedRecipients:failedRecipients.value});confirmationId.value=result.confirmation.confirmationId;await lookupSend()})
const testAccount=()=>guard('Testing SMTP connection',()=>invoke('email_account_test',{accountId:accounts.draft.id}).then(()=>{}))
const saveAccount=()=>guard('Saving account',()=>accounts.save())
const removeAccount=()=>guard('Deleting account',async()=>{await invoke('email_account_delete',{id:accounts.draft.id});newAccount();await accounts.load()})
const makeDefault=()=>guard('Setting default account',async()=>{await invoke('email_account_set_default',{id:accounts.draft.id});await accounts.load()})
function newAccount(){accounts.setDraft({displayName:'',email:'',password:'',smtpHost:'',smtpPort:587,smtpSecurity:'STARTTLS',imapHost:'',imapPort:993,imapSecurity:'SSL',defaultAccount:false})}
onMounted(loadArchive)
</script>
<template><v-card class="surface" variant="flat"><v-card-title class="d-flex"><v-btn-toggle v-model="view" mandatory color="primary"><v-btn value="records">Records</v-btn><v-btn value="accounts">Accounts</v-btn></v-btn-toggle></v-card-title><v-card-text><v-alert v-if="error" type="error" class="mb-4">{{error}}</v-alert>
<template v-if="view==='records'"><v-btn-toggle v-model="recordKind" mandatory class="mb-4"><v-btn value="archive">Archive</v-btn><v-btn value="send">Send status</v-btn></v-btn-toggle><template v-if="recordKind==='archive'"><v-table><thead><tr><th>Subject</th><th>From</th><th>Folder</th><th>Archived</th></tr></thead><tbody><tr v-for="item in archive.messages" :key="String(item.id)" @click="openDetail(item.id)"><td>{{item.subject}}</td><td>{{item.fromAddress}}</td><td>{{item.folder}}</td><td>{{item.archivedAt}}</td></tr></tbody></v-table><div class="pager"><v-btn :disabled="archive.offset===0" @click="archive.previousPage();loadArchive()">Previous</v-btn><span>Page {{Math.floor(archive.offset/archive.limit)+1}}</span><v-btn @click="archive.nextPage();loadArchive()">Next</v-btn></div><v-sheet v-if="detail" class="detail pa-4 mt-4" rounded><pre>{{detail}}</pre></v-sheet></template><template v-else><div class="inline-fields"><v-text-field v-model="confirmationId" label="Confirmation ID"/><v-btn @click="lookupSend">Look up</v-btn></div><v-sheet v-if="sendRecord" class="pa-4" rounded><pre>{{sendRecord}}</pre><v-combobox v-model="failedRecipients" multiple chips label="Failed recipients to retry"/><v-btn color="primary" :disabled="!failedRecipients.length" @click="retry">Prepare retry</v-btn></v-sheet></template></template>
<template v-else><div class="account-layout"><v-list><v-list-item v-for="account in accounts.accounts" :key="account.id" :title="account.displayName" :subtitle="account.email" @click="accounts.setDraft(account)"/><v-list-item prepend-icon="mdi-plus" title="New account" @click="newAccount"/></v-list><div><v-text-field v-model="accounts.draft.displayName" label="Display name"/><v-text-field v-model="accounts.draft.email" label="Email"/><v-text-field v-model="accounts.draft.password" label="Password (leave blank to keep existing)" type="password" autocomplete="new-password"/><div class="inline-fields"><v-text-field v-model="accounts.draft.smtpHost" label="SMTP host"/><v-text-field v-model.number="accounts.draft.smtpPort" label="Port" type="number"/><v-select v-model="accounts.draft.smtpSecurity" :items="['SSL','STARTTLS','PLAIN']" label="Security"/></div><div class="inline-fields"><v-text-field v-model="accounts.draft.imapHost" label="IMAP host"/><v-text-field v-model.number="accounts.draft.imapPort" label="Port" type="number"/><v-select v-model="accounts.draft.imapSecurity" :items="['SSL','STARTTLS','PLAIN']" label="Security"/></div><v-checkbox v-model="accounts.draft.defaultAccount" label="Default sending account"/><p class="hint">SMTP Test validates outgoing connectivity. Use Collect Mail to validate the IMAP account and folder.</p><div class="d-flex ga-2 justify-end"><v-btn v-if="accounts.draft.id" color="error" variant="text" @click="removeAccount">Delete</v-btn><v-btn v-if="accounts.draft.id&&!accounts.draft.defaultAccount" variant="tonal" @click="makeDefault">Make default</v-btn><v-btn variant="tonal" @click="testAccount">SMTP Test</v-btn><v-btn color="primary" @click="saveAccount">Save account</v-btn></div></div></div></template>
</v-card-text></v-card></template>
