package fan.summer.fengyu.ai.tools;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.json.JsonMapper;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;

/**
 * Small runtime validator for the JSON-Schema vocabulary emitted by FengYu contracts.
 *
 * <p>The CLI validates schemas while a plugin is built, but a worker can still return a value
 * that disagrees with its declared contract. This validator is the host-side trust boundary used
 * before plugin arguments cross the process boundary and before results enter Flow's shared value
 * channel. It intentionally implements the deterministic subset generated by the Java, Python,
 * and Go SDKs rather than pretending to be a general-purpose JSON-Schema engine.</p>
 */
public final class JsonSchemaContractValidator {
    private static final ObjectMapper JSON = JsonMapper.builder().findAndAddModules().build();

    private JsonSchemaContractValidator() {}

    public static void validate(Object value, JsonNode schema, String subject) {
        if (schema == null || schema.isNull() || schema.isMissingNode()) return;
        validateNode(JSON.valueToTree(value), schema, "$", subject);
    }

    /**
     * Validates plugin arguments after FengYu has bound opaque file placeholders. A generated AI
     * contract deliberately exposes resolved worker paths as strings, while the host temporarily
     * carries them as authenticated FileRef envelopes until {@code PluginProcessManager} resolves
     * the grant. Normalize only a structurally valid host FileRef at a string schema position;
     * every other value remains subject to ordinary schema validation.
     */
    public static void validateHostInput(Object value, JsonNode schema, String subject) {
        if (schema == null || schema.isNull() || schema.isMissingNode()) return;
        validateNode(hostContractView(JSON.valueToTree(value), schema), schema, "$", subject);
    }

    public static void validateJson(String value, JsonNode schema, String subject) {
        if (schema == null || schema.isNull() || schema.isMissingNode()) return;
        final JsonNode parsed;
        try {
            parsed = JSON.readTree(value);
        } catch (Exception error) {
            throw violation(subject, "$", "expected JSON matching the declared schema");
        }
        validateNode(parsed, schema, "$", subject);
    }

    /** True when a dotted / {@code [N]} path is declared by the schema. */
    public static boolean declaresPath(JsonNode schema, String path) {
        if (schema == null || schema.isNull() || schema.isMissingNode()) return true;
        List<String> segments = pathSegments(path);
        return declaresPath(schema, segments, 0);
    }

    private static void validateNode(JsonNode value, JsonNode schema, String path, String subject) {
        if (schema.isBoolean()) {
            if (!schema.booleanValue()) throw violation(subject, path, "value is forbidden by schema");
            return;
        }
        if (!schema.isObject()) return;

        validateCompositions(value, schema, path, subject);
        if (schema.has("const") && !schema.get("const").equals(value)) {
            throw violation(subject, path, "value does not match const");
        }
        JsonNode enumeration = schema.get("enum");
        if (enumeration != null && enumeration.isArray()) {
            boolean match = false;
            for (JsonNode candidate : enumeration) match |= candidate.equals(value);
            if (!match) throw violation(subject, path, "value is not one of the allowed enum values");
        }

        if (!matchesDeclaredType(value, schema.get("type"))) {
            throw violation(subject, path, "expected " + displayType(schema.get("type"))
                    + " but received " + valueType(value));
        }
        if (value == null || value.isNull()) return;

        if (value.isObject()) validateObject(value, schema, path, subject);
        if (value.isArray()) validateArray(value, schema, path, subject);
        if (value.isTextual()) validateString(value.textValue(), schema, path, subject);
        if (value.isNumber()) validateNumber(value, schema, path, subject);
    }

    private static void validateCompositions(JsonNode value, JsonNode schema,
                                             String path, String subject) {
        JsonNode allOf = schema.get("allOf");
        if (allOf != null && allOf.isArray()) {
            for (JsonNode branch : allOf) validateNode(value, branch, path, subject);
        }
        JsonNode anyOf = schema.get("anyOf");
        if (anyOf != null && anyOf.isArray() && !matchesAny(value, anyOf)) {
            throw violation(subject, path, "value does not match any allowed schema");
        }
        JsonNode oneOf = schema.get("oneOf");
        if (oneOf != null && oneOf.isArray()) {
            int matches = 0;
            for (JsonNode branch : oneOf) {
                if (matches(value, branch)) matches++;
            }
            if (matches != 1) throw violation(subject, path, "value must match exactly one schema");
        }
    }

    private static boolean matchesAny(JsonNode value, JsonNode schemas) {
        for (JsonNode branch : schemas) if (matches(value, branch)) return true;
        return false;
    }

    private static boolean matches(JsonNode value, JsonNode schema) {
        try {
            validateNode(value, schema, "$", "value");
            return true;
        } catch (IllegalArgumentException ignored) {
            return false;
        }
    }

    private static void validateObject(JsonNode value, JsonNode schema,
                                       String path, String subject) {
        JsonNode required = schema.get("required");
        if (required != null && required.isArray()) {
            for (JsonNode field : required) {
                if (field.isTextual() && !value.has(field.textValue())) {
                    throw violation(subject, path + "." + field.textValue(), "required value is missing");
                }
            }
        }
        JsonNode properties = schema.get("properties");
        value.fields().forEachRemaining(entry -> {
            JsonNode property = properties != null && properties.isObject()
                    ? properties.get(entry.getKey()) : null;
            if (property != null) {
                validateNode(entry.getValue(), property, path + "." + entry.getKey(), subject);
                return;
            }
            JsonNode additional = schema.get("additionalProperties");
            if (additional != null && additional.isBoolean() && !additional.booleanValue()) {
                throw violation(subject, path + "." + entry.getKey(), "additional property is not allowed");
            }
            if (additional != null && additional.isObject()) {
                validateNode(entry.getValue(), additional, path + "." + entry.getKey(), subject);
            }
        });
    }

    private static void validateArray(JsonNode value, JsonNode schema,
                                      String path, String subject) {
        int size = value.size();
        if (schema.has("minItems") && size < schema.path("minItems").asInt()) {
            throw violation(subject, path, "must contain at least " + schema.path("minItems").asInt() + " item(s)");
        }
        if (schema.has("maxItems") && size > schema.path("maxItems").asInt()) {
            throw violation(subject, path, "must contain at most " + schema.path("maxItems").asInt() + " item(s)");
        }
        JsonNode items = schema.get("items");
        if (items != null) {
            for (int index = 0; index < size; index++) {
                validateNode(value.get(index), items, path + "[" + index + "]", subject);
            }
        }
    }

    private static void validateString(String value, JsonNode schema,
                                       String path, String subject) {
        if (schema.has("minLength") && value.length() < schema.path("minLength").asInt()) {
            throw violation(subject, path, "is shorter than minLength");
        }
        if (schema.has("maxLength") && value.length() > schema.path("maxLength").asInt()) {
            throw violation(subject, path, "is longer than maxLength");
        }
        if (schema.has("pattern")) {
            try {
                if (!Pattern.compile(schema.path("pattern").asText()).matcher(value).find()) {
                    throw violation(subject, path, "does not match the declared pattern");
                }
            } catch (PatternSyntaxException error) {
                throw violation(subject, path, "declares an invalid pattern");
            }
        }
    }

    private static void validateNumber(JsonNode value, JsonNode schema,
                                       String path, String subject) {
        double number = value.doubleValue();
        if (schema.has("minimum") && number < schema.path("minimum").doubleValue()) {
            throw violation(subject, path, "is below minimum");
        }
        if (schema.has("maximum") && number > schema.path("maximum").doubleValue()) {
            throw violation(subject, path, "is above maximum");
        }
    }

    private static boolean matchesDeclaredType(JsonNode value, JsonNode type) {
        if (type == null || type.isNull() || type.isMissingNode()) return true;
        if (type.isArray()) {
            for (JsonNode candidate : type) {
                if (candidate.isTextual() && matchesType(value, candidate.textValue())) return true;
            }
            return false;
        }
        return !type.isTextual() || matchesType(value, type.textValue());
    }

    private static boolean matchesType(JsonNode value, String type) {
        return switch (type) {
            case "null" -> value == null || value.isNull();
            case "object" -> value != null && value.isObject();
            case "array" -> value != null && value.isArray();
            case "string" -> value != null && value.isTextual();
            case "integer" -> value != null && value.isIntegralNumber();
            case "number" -> value != null && value.isNumber();
            case "boolean" -> value != null && value.isBoolean();
            default -> true;
        };
    }

    private static String displayType(JsonNode type) {
        return type == null ? "declared type" : type.toString();
    }

    private static String valueType(JsonNode value) {
        if (value == null || value.isNull()) return "null";
        if (value.isObject()) return "object";
        if (value.isArray()) return "array";
        if (value.isTextual()) return "string";
        if (value.isIntegralNumber()) return "integer";
        if (value.isNumber()) return "number";
        if (value.isBoolean()) return "boolean";
        return value.getNodeType().name().toLowerCase();
    }

    private static boolean declaresPath(JsonNode schema, List<String> segments, int index) {
        if (index >= segments.size()) return true;
        for (String composition : List.of("allOf", "anyOf", "oneOf")) {
            JsonNode branches = schema.path(composition);
            if (branches.isArray()) {
                for (JsonNode branch : branches) {
                    if (declaresPath(branch, segments, index)) return true;
                }
            }
        }
        String segment = segments.get(index);
        if (segment.chars().allMatch(Character::isDigit)) {
            JsonNode items = schema.get("items");
            return items != null && declaresPath(items, segments, index + 1);
        }
        JsonNode properties = schema.path("properties");
        JsonNode property = properties.isObject() ? properties.get(segment) : null;
        if (property != null) return declaresPath(property, segments, index + 1);
        JsonNode additional = schema.get("additionalProperties");
        return additional != null && (!additional.isBoolean() || additional.booleanValue());
    }

    private static JsonNode hostContractView(JsonNode value, JsonNode schema) {
        if (looksLikeFileRef(value) && schemaAllowsType(schema, "string")) {
            return JSON.getNodeFactory().textNode(value.path("name").asText(value.path("id").asText()));
        }
        if (value != null && value.isObject()) {
            var normalized = JSON.createObjectNode();
            JsonNode properties = schema.path("properties");
            value.fields().forEachRemaining(entry -> {
                JsonNode childSchema = properties.isObject() ? properties.get(entry.getKey()) : null;
                if (childSchema == null) childSchema = schema.path("additionalProperties");
                normalized.set(entry.getKey(), childSchema == null || childSchema.isMissingNode()
                        ? entry.getValue() : hostContractView(entry.getValue(), childSchema));
            });
            return normalized;
        }
        if (value != null && value.isArray()) {
            var normalized = JSON.createArrayNode();
            JsonNode items = schema.path("items");
            for (JsonNode child : value) {
                normalized.add(items.isMissingNode() ? child : hostContractView(child, items));
            }
            return normalized;
        }
        return value;
    }

    private static boolean looksLikeFileRef(JsonNode value) {
        if (value == null || !value.isObject()
                || !value.path("id").isTextual()
                || !value.path("name").isTextual()
                || !value.path("kind").isTextual()
                || !value.path("access").isTextual()) return false;
        return ("file".equals(value.path("kind").asText())
                || "directory".equals(value.path("kind").asText()))
                && ("read".equals(value.path("access").asText())
                || "write".equals(value.path("access").asText())
                || "read-write".equals(value.path("access").asText()));
    }

    private static boolean schemaAllowsType(JsonNode schema, String expected) {
        JsonNode type = schema.get("type");
        if (type != null && (expected.equals(type.asText())
                || type.isArray() && java.util.stream.StreamSupport.stream(type.spliterator(), false)
                        .anyMatch(candidate -> expected.equals(candidate.asText())))) return true;
        for (String composition : List.of("allOf", "anyOf", "oneOf")) {
            JsonNode branches = schema.path(composition);
            if (branches.isArray()) {
                for (JsonNode branch : branches) {
                    if (schemaAllowsType(branch, expected)) return true;
                }
            }
        }
        return false;
    }

    private static List<String> pathSegments(String path) {
        if (path == null || path.isBlank()) return List.of();
        String normalized = path.startsWith(".") ? path.substring(1) : path;
        normalized = normalized.replace("[", ".").replace("]", "");
        List<String> segments = new ArrayList<>();
        for (String segment : normalized.split("\\.")) {
            if (!segment.isBlank()) segments.add(segment);
        }
        return segments;
    }

    private static IllegalArgumentException violation(String subject, String path, String detail) {
        return new IllegalArgumentException(subject + " violates its JSON schema at " + path + ": " + detail);
    }
}
