export default {
  nav: { compose: 'Compose', batch: 'Batch Send', contacts: 'Contacts', archive: 'Archive', records: 'Send Records', accounts: 'Account Settings' },
  common: { save: 'Save', cancel: 'Cancel', delete: 'Delete', search: 'Search', add: 'Add', close: 'Close', loading: 'Loading…', none: 'None' },
  compose: { title: 'Compose email', direct: 'Direct addresses', contactTags: 'Contact tags', recipientMode: 'Recipient mode', from: 'From account', to: 'To', cc: 'CC', subject: 'Subject', bodyPlaceholder: 'Write your message…', attach: 'Add attachment', review: 'Review and send', separateMessages: '{count} separate messages', directHint: '{count} primary recipients', wordNormalized: 'Word formatting was cleaned and preserved safely.', draftSaved: 'Draft saved locally', draftPending: 'Draft changes save automatically', ready: 'Ready for confirmation review', validation: 'Choose an account, recipients, and message body', previewTitle: 'Message preview', noSubject: 'No subject', previewEmpty: 'Your message preview appears here.', sendResult: 'Sent {sent}, failed {failed}', loadTags: 'Loading contact tags', selectAttachment: 'Selecting attachment', prepareAction: 'Preparing email', sendAction: 'Sending email', cancelAction: 'Cancelling send' },
  batch: { title: 'Send by attachment tag', directory: 'Choose attachment directory', noDirectory: 'No attachment directory selected', recipientGroups: 'Sending group tags', ccGroups: 'CC group tags', commonAttachments: 'Common attachments', tagAttachments: 'Tag attachments', preview: 'Message preview', previewEmpty: 'Choose a directory, sending groups, and message body to generate the preview.', ignoredFiles: 'Ignored files', skippedTags: 'Skipped tags', review: 'Generate and review {count} messages', refresh: 'Refresh preview', formula: 'For each filename tag T: To = contacts tagged T ∩ sending groups; CC = contacts tagged T ∩ CC groups. To takes precedence over CC.', loadTags: 'Loading group tags', selectDirectory: 'Selecting attachment directory', selectCommon: 'Selecting common attachment', previewAction: 'Generating batch preview', prepareAction: 'Preparing batch', sendAction: 'Sending batch', cancelAction: 'Cancelling batch' },
  contacts: { title: 'Contacts', newContact: 'New contact', manageTags: 'Manage tags', assignTags: 'Assign tags', name: 'Name', email: 'Email', notes: 'Notes' },
  archive: { title: 'Mail archive', collect: 'Collect now', account: 'IMAP account', folder: 'Folder', range: 'Date range', output: 'Archive directory', processed: 'Processed', new: 'New', duplicates: 'Duplicates', failed: 'Failed' },
  records: { title: 'Send records', status: 'Status', progress: 'Progress', mode: 'Mode', sentAt: 'Sent at', partial: 'Partially failed' },
  accounts: { title: 'Account settings', loading: 'Loading accounts', newAccount: 'Add account', passwordHelp: 'Leave blank to keep the saved password', smtp: 'SMTP server', imap: 'IMAP server', test: 'Test SMTP', defaultAccount: 'Default sending account' },
  confirmation: { title: 'Confirm send', approve: 'Confirm send', reject: 'Reject', expires: 'Expires {time}' },
  editor: { toolbar: 'Formatting toolbar', bold: 'Bold', italic: 'Italic', underline: 'Underline', heading: 'Heading', fontSize: 'Font size', color: 'Text color', alignLeft: 'Align left', alignCenter: 'Align center', alignRight: 'Align right', bullets: 'Bullets', numbering: 'Numbering', link: 'Link', linkPrompt: 'Enter a safe http, https, or mailto link', table: 'Table', clear: 'Clear formatting' },
  errors: { unknown: 'Email operation failed. Try again.', actionFailed: '{action} failed: {detail}' },
}
