export default {
  nav: { compose: 'Compose', batch: 'Batch Send', contacts: 'Contacts', archive: 'Archive', records: 'Send Records', accounts: 'Account Settings' },
  common: { save: 'Save', cancel: 'Cancel', confirm: 'Confirm', delete: 'Delete', search: 'Search', add: 'Add', close: 'Close', loading: 'Loading…', none: 'None', previous: 'Previous', next: 'Next', page: 'Page {page}' },
  compose: { title: 'Compose email', direct: 'Direct addresses', contactTags: 'Contact tags', recipientMode: 'Recipient mode', from: 'From account', to: 'To', cc: 'CC', subject: 'Subject', bodyPlaceholder: 'Write your message…', attach: 'Add attachment', review: 'Review and send', separateMessages: '{count} separate messages', directHint: '{count} primary recipients', wordNormalized: 'Word formatting was cleaned and preserved safely.', draftSaved: 'Draft saved locally', draftPending: 'Draft changes save automatically', ready: 'Ready for confirmation review', validation: 'Choose an account, recipients, and message body', previewTitle: 'Message preview', noSubject: 'No subject', previewEmpty: 'Your message preview appears here.', sendResult: 'Sent {sent}, failed {failed}', loadTags: 'Loading contact tags', selectAttachment: 'Selecting attachment', prepareAction: 'Preparing email', sendAction: 'Sending email', cancelAction: 'Cancelling send' },
  batch: { title: 'Send by attachment tag', directory: 'Choose attachment directory', noDirectory: 'No attachment directory selected', recipientGroups: 'Sending group tags', ccGroups: 'CC group tags', commonAttachments: 'Common attachments', tagAttachments: 'Tag attachments', preview: 'Message preview', previewEmpty: 'Choose a directory, sending groups, and message body to generate the preview.', ignoredFiles: 'Ignored files', skippedTags: 'Skipped tags', review: 'Generate and review {count} messages', refresh: 'Refresh preview', formula: 'For each filename tag T: To = contacts tagged T ∩ sending groups; CC = contacts tagged T ∩ CC groups. To takes precedence over CC.', loadTags: 'Loading group tags', selectDirectory: 'Selecting attachment directory', selectCommon: 'Selecting common attachment', previewAction: 'Generating batch preview', prepareAction: 'Preparing batch', sendAction: 'Sending batch', cancelAction: 'Cancelling batch' },
  contacts: { title: 'Contacts', newContact: 'New contact', editContact: 'Edit contact', manageTags: 'Manage tags', assignTags: 'Assign tags', filterTag: 'Filter by tags', newTag: 'New tag', name: 'Name', email: 'Email', notes: 'Notes', loadAction: 'Loading contacts', saveAction: 'Saving contact', deleteAction: 'Deleting contact', deleteConfirm: 'Delete this contact?', tagSaveAction: 'Saving tag', tagDeleteAction: 'Deleting tag', tagDeleteConfirm: 'Delete this tag?', assignAction: 'Assigning tags' },
  archive: { title: 'Mail archive', collect: 'Collect now', account: 'IMAP account', folder: 'Folder', range: 'Date range', from: 'From', to: 'To', output: 'Choose archive directory', processed: 'Processed', new: 'New', duplicates: 'Duplicates', failed: 'Failed', results: 'Archived messages', sender: 'Sender', archivedAt: 'Archived at', selectOutput: 'Selecting archive directory', collectAction: 'Collecting mail', loadAction: 'Loading archive', detailAction: 'Loading message detail' },
  records: { title: 'Send records', search: 'Search confirmation, account, subject, or recipient', tasks: 'Send tasks', messages: 'Message results', confirmationId: 'Confirmation ID', status: 'Status', progress: 'Progress', mode: 'Mode', account: 'Account', error: 'Error', updated: 'Updated', sentAt: 'Sent at', partial: 'Partially failed', loadAction: 'Loading send records' },
  accounts: { title: 'Account settings', loading: 'Loading accounts', newAccount: 'Add account', displayName: 'Display name', password: 'Password', passwordHelp: 'Leave blank to keep the saved password', smtpSection: 'Outgoing · SMTP', smtp: 'SMTP server', port: 'Port', security: 'Security', testSmtp: 'Test SMTP', imapSection: 'Incoming · IMAP', imap: 'IMAP server', testImap: 'Test IMAP', defaultAccount: 'Default sending account', makeDefault: 'Make default', testAction: 'Testing connection', testSuccess: 'Connection succeeded', saveAction: 'Saving account', saved: 'Account saved', defaultAction: 'Setting default account', deleteAction: 'Deleting account', deleteConfirm: 'Delete this account?' },
  confirmation: { title: 'Confirm send', approve: 'Confirm send', reject: 'Reject', expires: 'Expires {time}' },
  editor: { toolbar: 'Formatting toolbar', bold: 'Bold', italic: 'Italic', underline: 'Underline', heading: 'Heading', fontSize: 'Font size', color: 'Text color', alignLeft: 'Align left', alignCenter: 'Align center', alignRight: 'Align right', bullets: 'Bullets', numbering: 'Numbering', link: 'Link', linkPrompt: 'Enter a safe http, https, or mailto link', table: 'Table', clear: 'Clear formatting' },
  errors: { unknown: 'Email operation failed. Try again.', actionFailed: '{action} failed: {detail}' },
}
