export default {
  nav: { compose: '写邮件', batch: '批量发送', contacts: '联系人', archive: '邮件归档', records: '发送记录', accounts: '账户设置' },
  common: { save: '保存', cancel: '取消', confirm: '确认', delete: '删除', search: '搜索', add: '添加', close: '关闭', loading: '加载中…', none: '无', previous: '上一页', next: '下一页', page: '第 {page} 页' },
  compose: { title: '写一封邮件', direct: '直接输入地址', contactTags: '按联系人标签群发', recipientMode: '收件方式', from: '发件账户', to: '收件人', cc: '抄送', subject: '主题', bodyPlaceholder: '请输入邮件正文…', attach: '添加附件', review: '检查并发送', separateMessages: '共 {count} 封独立邮件', directHint: '共 {count} 位收件人', wordNormalized: '已安全清理并保留 Word 格式。', draftSaved: '草稿已保存到本机', draftPending: '草稿修改将自动保存', ready: '可以进入确认检查', validation: '请选择账户、收件人并填写正文', previewTitle: '邮件预览', noSubject: '无主题', previewEmpty: '邮件预览将显示在这里。', sendResult: '已发送 {sent}，失败 {failed}', loadTags: '加载联系人标签', selectAttachment: '选择附件', prepareAction: '准备邮件', sendAction: '发送邮件', cancelAction: '取消发送' },
  batch: { title: '按附件标签批量发送', directory: '选择附件目录', noDirectory: '尚未选择附件目录', recipientGroups: '发送群组标签', ccGroups: '抄送群组标签', commonAttachments: '公共附件', tagAttachments: '标签附件', preview: '邮件预览', previewEmpty: '请选择附件目录、发送群组并填写正文，以生成预览。', ignoredFiles: '忽略文件', skippedTags: '跳过标签', review: '生成并检查 {count} 封邮件', refresh: '刷新预览', formula: '对每个文件名标签 T：收件人 = 标签 T 联系人 ∩ 发送群组；抄送 = 标签 T 联系人 ∩ 抄送群组。收件人优先于抄送。', loadTags: '加载群组标签', selectDirectory: '选择附件目录', selectCommon: '选择公共附件', previewAction: '生成批量预览', prepareAction: '准备批量邮件', sendAction: '发送批量邮件', cancelAction: '取消批量发送' },
  contacts: { title: '联系人', newContact: '新建联系人', editContact: '编辑联系人', manageTags: '管理标签', assignTags: '批量添加标签', filterTag: '按标签筛选', newTag: '新标签', name: '姓名', email: '邮箱', notes: '备注', loadAction: '加载联系人', saveAction: '保存联系人', deleteAction: '删除联系人', deleteConfirm: '确定删除该联系人吗？', tagSaveAction: '保存标签', tagDeleteAction: '删除标签', tagDeleteConfirm: '确定删除该标签吗？', assignAction: '分配标签' },
  archive: { title: '邮件归档', collect: '开始收取', account: 'IMAP 账户', folder: '文件夹', range: '时间范围', from: '开始时间', to: '结束时间', output: '选择归档目录', processed: '已处理', new: '新增', duplicates: '重复', failed: '失败', results: '归档邮件', sender: '发件人', archivedAt: '归档时间', selectOutput: '选择归档目录', collectAction: '收取邮件', loadAction: '加载归档记录', detailAction: '加载邮件详情' },
  records: { title: '发送记录', search: '搜索确认编号、账户、主题或收件人', tasks: '发送任务', messages: '邮件结果', confirmationId: '确认编号', status: '状态', progress: '进度', mode: '模式', account: '账户', error: '错误', updated: '更新时间', sentAt: '发送时间', partial: '部分失败', loadAction: '加载发送记录' },
  accounts: { title: '账户设置', loading: '正在加载账户', newAccount: '添加账户', displayName: '显示名称', password: '密码', passwordHelp: '留空则保持已保存密码', smtp: 'SMTP 发件服务器', imap: 'IMAP 收件服务器', port: '端口', security: '安全方式', test: '测试 SMTP', defaultAccount: '默认发件账户', makeDefault: '设为默认', testAction: '测试 SMTP 连接', testSuccess: 'SMTP 连接成功', saveAction: '保存账户', saved: '账户已保存', defaultAction: '设置默认账户', deleteAction: '删除账户', deleteConfirm: '确定删除该账户吗？' },
  confirmation: { title: '确认发送', approve: '确认发送', reject: '拒绝', expires: '有效期至 {time}' },
  editor: { toolbar: '格式工具栏', bold: '加粗', italic: '斜体', underline: '下划线', heading: '标题', fontSize: '字号', color: '文字颜色', alignLeft: '左对齐', alignCenter: '居中', alignRight: '右对齐', bullets: '项目符号', numbering: '编号', link: '链接', linkPrompt: '请输入安全的 http、https 或 mailto 链接', table: '表格', clear: '清除格式' },
  errors: { unknown: '邮件操作失败，请重试。', actionFailed: '{action}失败：{detail}' },
}
