package fan.summer.zhiflow.database.entity.setting.email;

import lombok.Data;

/**
 * Entity representing an email tag used for categorization.
 * <p>
 * Tags are simple label strings used to organize email addresses
 * in the address book for easier filtering and selection.
 *
 * @since 3.0.0
 */
@Data
public class EmailTagEntity {
    /** Primary key, auto-generated by the database. */
    private Long id;

    /** The tag label string (e.g., {@code "work"}, {@code "family"}). */
    private String tag;
}
